import { Navbar } from "@/components/Navbar";
import {
  AdhdTitlePage,
  ReadabilityPage,
  IntuitivePage,
  DecisionFatiguePage,
  DistractionsPage,
} from "@/components/sections";
import { Container, CssBaseline, ThemeProvider, Typography, createTheme } from "@mui/material";
import Head from "next/head";

const theme = createTheme({
  typography: {
    h2: {
      fontSize: "3rem",
      fontWeight: 800,
      letterSpacing: "0.005em",
      paddingBottom: "10px",
    },
    h3: {
      fontSize: "1.5rem",
      fontWeight: 500,
      letterSpacing: "0.01em",
      paddingTop: "10px",
      paddingBottom: "5px",
    },
    body1: {
      fontFamily: "sans-serif",
      letterSpacing: "0.1px",
    },
    body2: {
      maxWidth: "50%",
      fontFamily: "monospace",
    },
  },
  palette: {
    secondary: {
      main: "#0000FF",
    },
  },
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CssBaseline />
        <ThemeProvider theme={theme}>
          <div>
            <Navbar />
            <AdhdTitlePage />
            <ReadabilityPage />
            <DecisionFatiguePage />
            <IntuitivePage />
            <DistractionsPage />
          </div>
        </ThemeProvider>
      </main>
    </>
  );
}
