import { Navbar } from "@/components/Navbar";
import {
  AdhdTitlePage,
  ReadabilityPage,
  IntuitivePage,
  DecisionFatiguePage,
  DistractionsPage, ProjectEndPage
} from "@/components/sections";
import { Container, CssBaseline, ThemeProvider, Typography, createTheme, Box } from "@mui/material";
import Head from "next/head";

const breakpoints = {
  values: {
    xs: 0,
    sm: 600,
    md: 900,
    lg: 1200,
    xl: 1500
  }
};


const theme = createTheme({
  breakpoints,
  box: {
    maxWidth: "100%",
    wordWrap: "normal"
    // Add any other styles you need for the box
  },
  typography: {
    fontFamily: `"Red Hat Display",sans-serif`,
    // fontFamily: `"Lexend",sans-serif`,
    // fontFamily: `"Poppins",sans-serif`,
    // fontFamily: `"Roboto",sans-serif`,
    // fontFamily: `"Red Hat Display",sans-serif`,
    h1: {
      fontSize: "6rem",
      fontWeight: 900,
      letterSpacing: "-0.01em",
      paddingBottom: "15px",
      [`@media screen and (min-width: ${breakpoints.values.sm}px)`]: {
        fontSize: "4.5rem"
      },
      [`@media screen and (max-width: ${breakpoints.values.sm}px)`]: {
        fontSize: "3.5rem"
      },
      [`@media screen and (min-width: ${breakpoints.values.md}px)`]: {
        fontSize: "5.5rem"

      },
      [`@media screen and (min-width: ${breakpoints.values.lg}px)`]: {
        fontSize: "6rem"

      }
    },

    h2: {
      fontSize: "4rem",
      fontWeight: 900,
      letterSpacing: "-0.01em",
      paddingBottom: "15px",
      [`@media screen and (max-width: ${breakpoints.values.sm}px)`]: {
        fontSize: "3rem"
      }
    },
    h3: {
      fontSize: "1.7rem",
      fontWeight: 700,
      letterSpacing: "0.01em",
      paddingTop: "10px",
      paddingBottom: "5px"
    },
    h4: {
      fontSize: "1.4rem",
      fontWeight: 700,
      letterSpacing: "0.01em",
      paddingTop: "10px",
      paddingBottom: "5px"
    },
    h5: {
      fontSize: "2.2rem",
      fontWeight: 600,
      letterSpacing: "0.01em",
      paddingTop: "10px",
      paddingBottom: "5px"
    },
    body1: {
      fontSize: "1rem",
      fontWeight: 400,
      fontFamily: `"Poppins",sans-serif`,
      letterSpacing: "0.1px",
      wordWrap: "break-word",
      [`@media screen and (max-width: ${breakpoints.values.sm}px)`]: {
        fontSize: "0.9rem"
      }
    },
    body2: {}
  },
  palette: {
    secondary: {
      main: "#0000FF"
    }

  }
});

export default function Home() {
  return (
    <>
      <Head>
        <title>ADHD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@100;200;300;400;500;600;700;800;900&family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Red+Hat+Display:wght@300;400;500;600;700;800;900&family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet" />

      </Head>
      <main>

          <CssBaseline />
          <ThemeProvider theme={theme}>
            <Box component="main" sx={{ paddingRight: "2px" }}>
              <Navbar />
              <AdhdTitlePage />
              <ReadabilityPage />
              <DecisionFatiguePage />
              <IntuitivePage />
              <ProjectEndPage />
              {/*<DistractionsPage />*/}
            </Box>
          </ThemeProvider>

      </main>
    </>
  );
}
